version: '3.9'

services:
  gateway-service:
    build: .
    container_name: gateway-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "5050:5050"
    networks:
      - usernet

networks:
  usernet:
    driver: bridge

volumes:
  postgres_data:
